---
type: html
tbl-cap-location: top
tbl-colwidths: [35,20,20,25]
---

```{=html}
<style scoped>
table {
  font-size: 13px;
}
</style>
<style type="text/css">
caption, .table-caption {
  text-align: left;
}
</style>
```
# Supplementary Information

(first draft)

## Data sources

This project combines multiple databases to incorporate a larger number of explanatory/contextual variables than Son et al., 2022. We expanded the number of variables to aid the interpretation of our results in the context of the river network structure.

The bulk of the input data for our analysis comes from tabular data for:

1.  Catchment and stream networks attributes: based on the report ["An Enhanced Hydrologic Stream Network Based on the NHDPlus Medium Resolution Dataset"](https://pubs.usgs.gov/sir/2019/5127/sir20195127.pdf)
2.  Additional catchment attributes including land use from: [Select Attributes for NHDPlus Version 2.1 Reach Catchments and Modified Network Routed Upstream Watersheds for the Conterminous United States](https://www.sciencebase.gov/catalog/item/5669a79ee4b08895842a1d47)

The data are detailed below (this table needs to be updated before submission with the list of files used for the analysis):

| Source (Child Items)                                                                                                                                                                                                                                                                                                                                                                                                               | Attributes                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | Files                                | Purpose                                                                                                                                                                      |
|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| [An enhanced hydrologic stream network based on the NHDPlus medium resolution dataset](https://www.usgs.gov/publications/enhanced-hydrologic-stream-network-based-nhdplus-medium-resolution-dataset)                                                                                                                                                                                                                               | [ESNHDPlusV2_us: Database of Ancillary Hydrologic Attributes and Modified Routing for NHDPlus Version 2.1 Flowlines](https://www.sciencebase.gov/catalog/item/5d16509ee4b0941bde5d8ffe)                                                                                                                                                                                                                                                                                                                                                                    | E2NHDplusV2_us_final.xml             | Cumulative calculations along the stream networks (e.g. cumulative respiration, residence time, hyporheic exchange). It contains data about hydrosequence, FromNode, ToNode. |
|                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | e2nhdplusv2_us_csv.zip               | Cumulative calculations along the stream networks (e.g. cumulative respiration, residence time, hyporheic exchange). It contains data about hydrosequence, FromNode, ToNode. |
| [Select Climate and Water Balance Model Attributes for NHDPlus Version 2.1 Reach Catchments and Modified Network Routed Upstream Watersheds for the Conterminous United States](https://www.sciencebase.gov/catalog/item/566f6c76e4b09cfe53ca77fe "Select Climate and Water Balance Model Attributes for NHDPlus Version 2.1 Reach Catchments and Modified Network Routed Upstream Watersheds for the Conterminous United States") | [Attributes for NHDPlus Version 2.1 Reach Catchments and Modified Routed Upstream Watersheds for the Conterminous United States: Annual Average Actual Evapotranspiration (millimeters) from 2014 - 2015](https://www.sciencebase.gov/catalog/item/57ffb2c4e4b0824b2d16f4c3 "Attributes for NHDPlus Version 2.1 Reach Catchments and Modified Routed Upstream Watersheds for the Conterminous United States: Annual Average Actual Evapotranspiration (millimeters) from 2014 - 2015")                                                                     | NHDV2_Annual_AET_WB1415_CONUS.xml    | Potential: Intermittent analysis                                                                                                                                             |
|                                                                                                                                                                                                                                                                                                                                                                                                                                    | [Attributes for NHDPlus Version 2.1 Reach Catchments and Modified Routed Upstream Watersheds for the Conterminous United States: Annual Average Precipitation (millimeters) from 1945-2015](https://www.sciencebase.gov/catalog/item/57bf5c07e4b0f2f0ceb75b1b "Attributes for NHDPlus Version 2.1 Reach Catchments and Modified Routed Upstream Watersheds for the Conterminous United States: Annual Average Precipitation (millimeters) from 1945-2015")                                                                                                 | PPT2001_ANN_CONUS.zip                | Climatic variables for the year 2001-corresponding with land use map used (files are on an annual basis).                                                                    |
|                                                                                                                                                                                                                                                                                                                                                                                                                                    | [Attributes for NHDPlus Version 2.1 Reach Catchments and Modified Routed Upstream Watersheds for the Conterminous United States: Annual Average Runoff (millimeters) from 1945 - 2015](https://www.sciencebase.gov/catalog/item/57bf5e25e4b0f2f0ceb75b77 "Attributes for NHDPlus Version 2.1 Reach Catchments and Modified Routed Upstream Watersheds for the Conterminous United States: Annual Average Runoff (millimeters) from 1945 - 2015")                                                                                                           | RUN2001_ANN_CONUS.zip                | Climatic variables for the year 2001-corresponding with land use map used (files are on an annual basis).                                                                    |
|                                                                                                                                                                                                                                                                                                                                                                                                                                    | [Attributes for NHDPlus Version 2.1 Reach Catchments and Modified Routed Upstream Watersheds for the Conterminous United States: Annual Average Runoff (millimeters) from 1945 - 2015](https://www.sciencebase.gov/catalog/item/57bf5e25e4b0f2f0ceb75b77 "Attributes for NHDPlus Version 2.1 Reach Catchments and Modified Routed Upstream Watersheds for the Conterminous United States: Annual Average Runoff (millimeters) from 1945 - 2015")                                                                                                           | TAV2001_ANN_CONUS.zip                | Climatic variables for the year 2001-corresponding with land use map used (files are on an annual basis).                                                                    |
| [Select Land Cover Attributes for NHDPlus Version 2.1 Reach Catchments and Modified Network Routed Upstream Watersheds for the Conterminous United States](https://www.sciencebase.gov/catalog/item/5669a834e4b08895842a1d49 "Select Land Cover Attributes for NHDPlus Version 2.1 Reach Catchments and Modified Network Routed Upstream Watersheds for the Conterminous United States")                                           | [Attributes for NHDPlus Version 2.1 Catchments and Modified Routing of Upstream Watersheds for the Conterminous United States: National Land Cover Database 2001 (NLCD 2001)](https://www.sciencebase.gov/catalog/item/5761b67de4b04f417c2d30ae "Attributes for NHDPlus Version 2.1 Catchments and Modified Routing of Upstream Watersheds for the Conterminous United States: National Land Cover Database 2001 (NLCD 2001)")                                                                                                                             | NLCD01_CAT_CONUS.zip                 | Landscape heterogeneity analysis and its influence on scaling behavior                                                                                                       |
|                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | NLCD01_ACC_CONUS.zip                 | Landscape heterogeneity analysis and its influence on scaling behavior                                                                                                       |
|                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | NLCD01_TOT_CONUS.zip                 | Landscape heterogeneity analysis and its influence on scaling behavior                                                                                                       |
|                                                                                                                                                                                                                                                                                                                                                                                                                                    | [Attributes for NHDPlus Version 2.1 Catchments and Modified Routing of Upstream Watersheds for the Conterminous United States: National Land Cover Database 2019 Versions for the Years 2001, 2004, 2006, 2008, 2011, 2013, 2016, and 2019](https://www.sciencebase.gov/catalog/item/63935b30d34e0de3a1efe082 "Attributes for NHDPlus Version 2.1 Catchments and Modified Routing of Upstream Watersheds for the Conterminous United States: National Land Cover Database 2019 Versions for the Years 2001, 2004, 2006, 2008, 2011, 2013, 2016, and 2019") | NLCD01_CAT_CONUS.txt                 | Landscape heterogeneity analysis and its influence on scaling behavior                                                                                                       |
|                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | NLCD01_TOT_CONUS.txt                 | Landscape heterogeneity analysis and its influence on scaling behavior                                                                                                       |
|                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | NLCD01_ACC_CONUS.txt                 | Landscape heterogeneity analysis and its influence on scaling behavior                                                                                                       |
| [Select Climate and Water Balance Model Attributes for NHDPlus Version 2.1 Reach Catchments and Modified Network Routed Upstream Watersheds for the Conterminous United States](https://www.sciencebase.gov/catalog/item/566f6c76e4b09cfe53ca77fe "Select Climate and Water Balance Model Attributes for NHDPlus Version 2.1 Reach Catchments and Modified Network Routed Upstream Watersheds for the Conterminous United States") | [Attributes for NHDPlus Version 2.1 Reach Catchments and Modified Routed Upstream Watersheds for the Conterminous United States: Average Monthly Runoff (mm) from McCabe and Wolock's Runoff Model Over Period of Record, 1951-2000](https://www.sciencebase.gov/catalog/item/573b5344e4b0dae0d5e3ad9c "Attributes for NHDPlus Version 2.1 Reach Catchments and Modified Routed Upstream Watersheds for the Conterminous United States: Average Monthly Runoff (mm) from McCabe and Wolock's Runoff Model Over Period of Record, 1951-2000")               | NHDV2_WB_Runoff_5100_CONUS_Final.xml | Possible: Intermittency analysis or interpretation                                                                                                                           |
|                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | WB5100_ACC_CONUS.zip                 | Possible: Intermittency analysis or interpretation                                                                                                                           |
|                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | WB5100_CAT_CONUS.zip                 | Possible: Intermittency analysis or interpretation                                                                                                                           |
|                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | WB5100_TOT_CONUS.zip                 | Possible: Intermittency analysis or interpretation                                                                                                                           |
| [STATSGO Soil Characteristics](https://www.sciencebase.gov/catalog/item/5728d6ace4b0b13d3918a992 "STATSGO Soil Characteristics")                                                                                                                                                                                                                                                                                                   | [Attributes for NHDPlus Version 2.1 Catchments and Modified Routing of Upstream Watersheds for the Conterminous United States: STATSGO Soil Characteristics, Text Attributes](https://www.sciencebase.gov/catalog/item/5728dd46e4b0b13d3918a9a7 "Attributes for NHDPlus Version 2.1 Catchments and Modified Routing of Upstream Watersheds for the Conterminous United States: STATSGO Soil Characteristics, Text Attributes")                                                                                                                             | STATSGO_TEXT_TOT_CONUS.zip           | Possible: relationship with residence time/ hyporheic exchange                                                                                                               |
|                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | STATSGO_TEXT_CAT_CONUS.zip           | Possible: relationship with residence time/ hyporheic exchange                                                                                                               |
|                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | STATSGO_TEXT_ACC_CONUS.zip           | Possible: relationship with residence time/ hyporheic exchange                                                                                                               |

: Data inputs with their corresponding purpose in the project design and execution
