---
title: "Land Use Dataset"
format: html
editor: visual
---

| e2nhdpv2 variable | New name               | Definition                                                                                                                                                                                   |
|-------------------|------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| ComID             | comid                  | Unique feature identifier from NHDPlus source data.                                                                                                                                          |
| FL_GNIS_Na        | stream_name            | From the Geographic Names Information System                                                                                                                                                 |
| LENGTHKM          | flowline_length_km     | Flowline length                                                                                                                                                                              |
| REACHCODE         | reach_code             | Unique flowline identifier. The first eight digits are the Watershed Boundary Dataset(WBD) HUC8.The next six digits are randomly assigned, sequential numbers that are unique within a HUC8. |
| StreamOrde        | stream_order           | Strahler stream order                                                                                                                                                                        |
| FromNode          | from_node              | Original NHDPlusV2 from node identifier                                                                                                                                                      |
| ToNode            | to_node                | Original NHDPlusV2 to node identifier                                                                                                                                                        |
| Hydroseq          | hydroseq               | Hydro sequence (upstream order) identifier                                                                                                                                                   |
| TotLngthKm        | tot_flowline_length_km | Total upstream flowline length in kilometers(km)                                                                                                                                             |
| CatAreaKm2        | cat_sink_area_km2      | Incremental catchment area (km2) including sinks                                                                                                                                             |
| TotAreaKM2        | tot_ups_area_km2       | Total upstream area (km2)                                                                                                                                                                    |
| CumAreaKm2        | cum_div_area_km2       | Cumulative div-based drainage area (km2), to account for the area upstream of a headwater node                                                                                               |
| IncAreaKm2        | inc_flowline_area_km2  | Incremental flowline drainage area (km2)                                                                                                                                                     |
| SLOPE             | slope                  | Channel slope (vert lenght/horiz length)                                                                                                                                                     |
| HUC_4             | huc_4                  | 4-Digit Hydrologic Unit                                                                                                                                                                      |

: Variables from e2nhdpv2, their definition and renaming
